Resources:

  MyCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: S3
        Location: codebuild-artifacts-pcls
      BadgeEnabled: true
      # BuildBatchConfig:
      #   BatchReportMode: REPORT_INDIVIDUAL_BUILDS
      #   CombineArtifacts: true
      #   ServiceRole: arn:aws:iam::823278056251:role/service-role/codebuild-pcls-build-service-role
      #   TimeoutInMins: 10
      ConcurrentBuildLimit: 1
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild:1
        Type: LINUX_CONTAINER
      LogsConfig:
        S3Logs:
          EncryptionDisabled: true
          Status: ENABLED
          Location: codebuild-artifacts-pcls
      Name: test-pipeline
      ServiceRole: arn:aws:iam::823278056251:role/service-role/codebuild-pcls-build-service-role
      Source:
        Type: GITHUB
        Location: https://github.com/etiennefrei/test-pipeline
      Triggers:
        BuildType: BUILD
      # FilterGroups:
      #   - - Type: EVENT
      #       Pattern: PUSH
      #   - - Type: EVENT
      #       Pattern: PULL_REQUEST_CREATED
        Webhook: true